- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/features/something/CreateTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaCreateTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaGetOverdueTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaGetTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/ProcessEngineBuilder.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
- src/integrationTest/resources/create_task.bpmn
- src/integrationTest/resources/getOverdueTask.dmn
- src/integrationTest/resources/getTaskId.dmn
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/ProcessVariables.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskClientService.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskService.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskToCreate.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/PojoTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskClientServiceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskServiceTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/api/CreateTaskRequestBuilder.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/api/CreateTaskRequestCreator.java
Create a new task if an appellant, rep or respondent hasn't dealt with a direction by the due date.
https://tools.hmcts.net/jira/browse/RWA-81
```
[ ] Yes
[X] No
```
> RWA-81 Create task to follow up directions

- Jenkinsfile_nightly
- build.gradle
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/PojoTest.java
https://tools.hmcts.net/jira/browse/RWA-95
- Setup mutation tests.
- Moved pojo tester to appropriate package
```
[ ] Yes
[ x] No
```
> RWA-95: Setup Mutation tests

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/features/something/CreateTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/GetWelcomeTest.java
- src/integrationTest/resources/application-integration.yaml
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/RootController.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/CallbackControllerAdvice.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ErrorLogger.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/RootControllerTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/CallbackControllerAdviceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ErrorLoggerTest.java
https://tools.hmcts.net/jira/browse/RWA-117
Added controller advice for exceptions.
Added env variable to control whether to also log the exception to the console.
```
[ ] Yes
[ x] No
```
> RWA-117: Added controller advice for exceptions.

- build.gradle
Remove lombok as its not used and dependabot is trying to upgrade it
> Remove lombok as its not used and dependabot is trying to upgrade it

- charts/wa-workflow-api/values.aat.template.yaml
Enables stacktrace by default in aat. 
Update values.aat.template.yaml
```
[ ] Yes
[x ] No
```
> Enables stacktrace by default in aat. 

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
- config/owasp/suppressions.xml
- infrastructure/main.tf
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/utils/AuthorizationHeadersProvider.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaGetOverdueTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaGetTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/config/SwaggerPublisherBaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/config/SwaggerPublisherTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/Application.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/AuthCheckerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/ServiceTokenGeneratorConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootIntegrationBaseTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootIntegrationTest.java
https://tools.hmcts.net/jira/browse/RWA-126
Added S2S token Security filters and configuration to protect endpoints.
```
[ ] Yes
[x ] No
```
> Rwa-126: Security Configuration

- src/integrationTest/resources/permissions_IA_Asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-154
Added permissions dmn table
```
[ ] Yes
[x ] No
```
> RWA-154: Add permissions for each role to all tasks as configuration

- src/integrationTest/resources/mapCaseData_IA_Asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-163
> update dmn with the new variables

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/CamundaClient.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskClientService.java
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/external/taskservice/TaskClientServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-183
> add charts and secret config

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-197
Upgrade azurerm to v2
```
[ ] Yes
[ x] No
```
> RWA-197: Upgrade azurerm version to v2

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-233
Fix terraform to pull s2s secret from s2s vault and copy into wa-vault
```
[ ] Yes
[x ] No
```
> RWA-233: Fix terraform to pull s2s secret from s2s vault and copy into wa-vault

- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/CamundaCreateTaskTest.java
- src/integrationTest/resources/create_task.bpmn
https://tools.hmcts.net/jira/browse/RWA-234
Added auto cancellation for create task BPMN
```
[ ] Yes
[ x ] No
```
> added workflow for auto cancellation

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnResult.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnValue.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnResponse.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/GetTaskDmnRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/GetTaskDmnResult.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ProcessVariables.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/SendMessageRequest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnRequestTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnResponseTest.java
Increase mutation test coverage
```
[ ] Yes
[ x] No
```
> Increase mutation test coverage

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskControllerTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/SendMessageRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
https://tools.hmcts.net/jira/browse/RWA-93
> RWA-93 add correlationKeys field in the send message body

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-305
> RWA-305 fix CVE-2020-28052

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
> added wait time to get task created

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- charts/wa-workflow-api/values.yaml
Enable db only in preview through chart values
```
[ ] Yes
[x ] No
```
> Enable db only in preview through chart values

- charts/wa-workflow-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-356
Bumping chart version to 3.4.4
```
[ ] Yes
[x ] No
```
> bumping chart version

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-279
https://tools.hmcts.net/jira/browse/RWA-201
> fix to release bpm change

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/IdempotencyTaskWorker.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/IdempotencyTaskWorkerTest.java
> add worker to process task

- Jenkinsfile_nightly
- audit.json
- security.sh
> Nightly dev

- Jenkinsfile_nightly
> enabled security scan

- src/main/resources/db/migration/V1.0.2__init_tables.sql
> Revert migration

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
> upraded gradle and lombok version

- build.gradle
- config/owasp/suppressions.xml
> CVE review

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
https://tools.hmcts.net/jira/browse/RWA-399
> add lock duration to ensure enough time to complete worker task

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/SendMessageRequest.java
https://tools.hmcts.net/jira/browse/RWA-376
Correlating multiple executions with correct property 'all'
```
[ ] Yes
[ x] No
```
> Correlating multiple executions with correct property

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-425
> clean up user

- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/service/IdempotencyKeysRepositoryJpaTest.java
- src/integrationTest/resources/application-integration.yaml
- src/integrationTest/resources/schema.sql
> add test to cover db query is case sensitive

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-475
Add launch darkly sdk key from vault
```
[ ] Yes
[ x] No
```
> RWA-475: add secret to values.yaml

- build.gradle
Remove old unnecessary libraries as camunda artefacts were moved to its own repo
```
[ ] Yes
[ x] No
```
> Remove camunda libraries

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/config/LaunchDarklyFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/config/SwaggerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/Application.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
- src/main/resources/application.yaml
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-486
Update swagger to v3 added require s2s headers configuration and functional test to avoid potential issues when updating via dependabot.
```
[ ] Yes
[ x] No
```
> RWA-486: Update Swagger

- charts/wa-workflow-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-496
Bump hmctspublic java chart version
```
[ ] Yes
[x ] No
```
> RWA-496: Bump hmctspublic java chart version

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
Fix CVE-2021-22112
```
[ ] Yes
[x ] No
```
> Fix CVE-2021-22112

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorkerTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/config/RestApiActions.java
https://tools.hmcts.net/jira/browse/RWA-514
Moving to taskVariables
Updated functional tests
```
[ ] Yes
[x ] No
```
> RWA-514: Moving to taskVariables

- build.gradle
- charts/wa-workflow-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-498
Replaced jcenter repo with mavenCentral
```
[ ] Yes
[x ] No
```
> Replaced jcenter repo with mavenCentral

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
Added defaults for exponential back off  fixes issues with camunda fetchAndLock errors
```
[ ] Yes
[x ] No
```
> Added default for exponential back off

- Jenkinsfile_nightly
- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- charts/wa-workflow-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-503
> clean up IDAM_URL since it's not used in the app

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
https://tools.hmcts.net/jira/browse/RWA-526
> update swagger api doc

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
Increase initial back off time and decrese max time
```
[ ] Yes
[ x] No
```
> Increase initial back off time and decrease max time

- audit.json
> ignoring crosssite scripting endpoints

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
> Updating swagger docs.

- audit.json
> Ignoring security scan issues

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnValue.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/CamundaClient.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/CamundaFeignConfiguration.java
https://tools.hmcts.net/jira/browse/RWA-532
https://tools.hmcts.net/jira/browse/RWA-310
Add camunda feign configuration.
Add ignore unknown to generic dmnValue pojo.
```
[ ] Yes
[x ] No
```
> RWA-532: Multicategories support

- security.sh
Add fix to address wa-workflow-api nightly build failure
```
[ ] Yes
[X ] No
```
> add fix to address nightly build failure

- security.sh
WA workflow api nightly fix - Access to new folder in security test report
```
[ ] Yes
[X ] No
```
> Access to new folder in security test report

- Jenkinsfile_nightly
- security.sh
https://tools.hmcts.net/jira/browse/RWA-649
Fix nightly build failure
```
[ ] Yes
[ X] No
```
> Fix nightly build failure

- build.gradle
> CVE 2021 27568 fix

- build.gradle
> tomcat cve fix

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/FeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/LaunchDarklyFeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/features/FeatureFlag.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/util/LaunchDarklyFeatureTogglerTest.java
https://tools.hmcts.net/jira/browse/RWA-629
```
[ ] Yes
[x ] No
```
> Updated warnings task service to support non IAC requirments

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
[RWA-706](https://tools.hmcts.net/jira/browse/RWA-706)
see ticket
```
[ ] Yes
[X ] No
```
> RWA-706 Enable Fortify in Nightly build

- config/owasp/suppressions.xml
> Suppress CVE-2020-23171 until it is fixed

- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnValue.java
https://tools.hmcts.net/jira/browse/RWA-615
```
[ ] Yes
[ x] No
```
> Rwa 615 master rebase

- infrastructure/state.tf
Added azuread provider to fix master build
```
[ ] Yes
[x ] No
```
> Fix to master build

- config/owasp/suppressions.xml
Bumping suppress until date
```
[ ] Yes
[x ] No
```
> [SH] bumping suppress until

- src/contractTest/java/uk/gov/hmcts/reform/waworkflowapi/consumer/wa/WorkflowSendMessageConsumerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskControllerTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/GetTaskDmnResult.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ProcessVariables.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/common/TaskToCreate.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaProcessVariablesTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskControllerTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-722
Remove group field
```
[ ] Yes
[ ] No
```
> feat:Remove group usage(RWA-722)

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/main/resources/application.yaml
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
[RWA-836](https://tools.hmcts.net/jira/browse/RWA-836)
https://tools.hmcts.net/jira/browse/RWA-836
```
[ ] Yes
[X ] No
```
> RWA-836 Update workflow API (ready for consumption by ExUI)

- charts/wa-workflow-api/Chart.yaml
Up the java chart version
```
[ ] Yes
[ ] No
```
> Refactor:Up the java chart version

- charts/wa-workflow-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-1199
Upgrading java chart version
```
[ ] Yes
[x] No
```
> RWA-1199 [SH] Upgrading java chart version

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1254
```
[ ] Yes
[X] No
```
> RWA-1254 CVE-2020-36518 suppressed

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1271
Supress postgres CVE temporarily. JIRA ticket is for CEH and workflow api
```
[ ] Yes
[X ] No
```
> RWA-1271 Supress postgress CVE

- config/owasp/suppressions.xml
> RWA-1280 - Fix nightly builds - wa-workflow-api

- build.gradle
- config/owasp/suppressions.xml
> RWA-1298 - spring boot upgrade to 2.6.6

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-1098
Autoscaling for R1
```
[ ] Yes
[X] No
```
> RWA-1098-autoscaling for R1

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskControllerTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/entities/SpecificStandaloneRequest.java
https://tools.hmcts.net/jira/browse/RWA-1198
Some tests were added for support wa jurisdiction
```
[ ] Yes
[X] No
```
> RWA-1198-some tests added for supporting wa jurisdiction

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1349
upgraded postgresql jdbc driver to 42.3.4 
```
[ ] Yes
[ ] No
```
> Rwa 1349 upgraded postgresql jdbc driver to 42.3.4

- .github/dependabot.yml
Changed dependabot schedule to weekly.
Disabled automatic rebase of dependabot PRs.
Cleaned up dependabot configuration.
```
[ ] Yes
[x ] No
```
> Dependabot configuration changes

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/entities/SpecificStandaloneRequest.java
https://tools.hmcts.net/jira/browse/RWA-1441
```
[ ] Yes
[X] No
```
> RWA-1441-role-assignment-id-in-additional properties

- infrastructure/main.tf
- infrastructure/variables.tf
Correcting the DB product name to follow conventions.
> correcting the db product name

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1700
CVE fix for postgres database driver
```
[ ] Yes
[X] No
```
> RWA-1700 CVE fix

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/config/LaunchDarklyFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/features/FeatureFlag.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
[RWA-1518](https://tools.hmcts.net/jira/browse/RWA-1518)
```
[ ] Yes
[x] No
```
> RWA-1518 Workflow API - remove R1 elements

- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-1730
Extend tests timeout to increase reliability
```
[ ] Yes
[X] No
```
> RWA-1730 extend timeout for tests

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1817
CVE-2022-31679, CVE-2022-38751 fixes
```
[ ] Yes
[x] No
```
> CVE-2022-31679, CVE-2022-38751 fixes

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1849
Upgraded:
org.owasp.dependencycheck 7.1.2 to 7.2.1
org.flywaydb.flyway 9.2.2 to 9.4.0
junit 5.9.0 to 5.9.1
pitest 1.9.4 to 1.9.6
testcontainers 1.17.3 to 1.17.4
log4j 2.18.0 to 2.19.0
spring-cloud-starter-openfeign 3.1.3 to 3.1.4
flyway-core 9.2.2 to 9.4.0
```
[ ] Yes
[x] No
```
> RWA-1849: Dependabot PRs merge for wa-workflow-api

- src/main/resources/application.yaml
[RWA-1852](https://tools.hmcts.net/jira/browse/RWA-1852)
```
[ ] Yes
[ X] No
```
> RWA-1852 whitelist task-management-api

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1968
CVE fixes - upgrade tomcat, springframework boot and springframework security
```
[ ] Yes
[x] No
```
> RWA-1968 - CVE fixes - upgrade tomcat, springframework boot and springframework security

- charts/wa-workflow-api/Chart.yaml
Updating Chart Version
```
[ ] Yes
[x] No
```
> Updating Chart Version

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/TaskManagementServiceApi.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaProcess.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaTask.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/CamundaClient.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/domain/taskconfiguration/request/NotesRequest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaTaskTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
[RWA-1896](https://tools.hmcts.net/jira/browse/RWA-1896)
```
[ ] Yes
[x] No
```
> RWA-1896 Warning message issue

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
https://tools.hmcts.net/jira/browse/RWA-2064
Amended au.com.dius.pact to version 4.1.8
```
[ ] Yes
[x] No
```
> RWA-2064 - Amended au.com.dius.pact to version 4.1.8

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2086
Suppress CVE-2021-37533 until proper fix. 
I have put a limit of 1st February 2023 to actually fix this issue.
```
[ ] Yes
[x] No
```
> RWA-2086 temporarily suppress CVE-2021-37533

- gradle/wrapper/gradle-wrapper.properties
RWA-2057 Updating Gradle Version to 7.6
```
[ ] Yes
[x] No
```
> RWA-2057 Updating Gradle Version to 7.6

- build.gradle
- config/owasp/suppressions.xml
RWA-2132 CVE-2020-36569 FIX for wa-workflow-api
```
[ ] Yes
[X] No
```
> RWA-2132 CVE FIX for wa-workflow-api

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/TaskManagementServiceApi.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-1955
```
[ ] Yes
[X] No
```
> RWA-1955-wa-task-management-api url standardized

- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ActivityInstance.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ActivityInstanceTest.java
- src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
[RWA-1868](https://tools.hmcts.net/jira/browse/RWA-1868)
```
[ ] Yes
[x] No
```
> RWA-1868 Enable and fix delay a task test

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2330
```
[ ] Yes
[ x] No
```
> RWA-2330: suppress CVE-2022-45688 

- .github/workflows/swagger.yml
- build.gradle
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientServiceTest.java
[RWA-1773](https://tools.hmcts.net/jira/browse/RWA-1773)
[RWA-2407](https://tools.hmcts.net/jira/browse/RWA-2407)
[RWA-1762](https://tools.hmcts.net/jira/browse/RWA-1762)
Support json type in initiation DMN
```
[ ] Yes
[ ] No
```
> Support json type in initiation DMN(RWA-1773)

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-2509
Suppress CVE-2023-20863
```
[ ] Yes
[ x ] No
```
> RWA-2509: Suppress CVE-2023-20863

- .gitignore
- Jenkinsfile_CNP
- Jenkinsfile_nightly
- bin/import-bpmn-diagram.sh
- bin/import-dmn-diagram.sh
- bin/import-wa-bpmn-diagram.sh
- bin/pull-latest-camunda-wa-files.sh
- bin/pull-latest-dmn-files.sh
- bin/pull-latest-release-asset.sh
- bin/utils/idam-lease-service-token.sh
- bin/wait-for.sh
- build.gradle
- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- charts/wa-workflow-api/values.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
- src/functionalTest/resources/application-functional.yaml
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/idempotency/IdempotencyTaskService.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/WorkflowApiTestingController.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/IdempotencyTaskServiceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/WorkflowApiTestingControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-803
```
[ ] Yes
[X] No
```
> RWA-803-Check FTs use AAT DB 

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-2280
Fix test reports
```
[ ] Yes
[x ] No
```
> RWA-2280 Fix test report coverage

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2601
CVE-2023-20883
```
[ ] Yes
[ x ] No
```
> RWA-2601: Address CVE-2023-20883

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2636
suppress CVE-2023-35116
```
[ ] Yes
[ x ] No
```
> RWA-2636: suppress cve

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2683
Suppress CVE : CVE-2023-34036
```
[ ] Yes
[ x ] No
```
> RWA-2683: suppress / fix cve CVE-2023-34036

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2702
Fix CVE-2020-8908 
```
[ ] Yes
[ X ] No
```
> RWA-2699: Fix CVE-2020-8908

- Jenkinsfile_CNP
- audit.json
https://tools.hmcts.net/jira/browse/RWA-2760
```
[ ] Yes
[x ] No
```
> Add OWASP Zaproxy alert to audit.json

- Jenkinsfile_CNP
- audit.json
https://tools.hmcts.net/jira/browse/RWA-2760
```
[ ] Yes
[ x] No
```
> RWA-2760: Correct audit.json

- charts/wa-workflow-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2816
Remove dependency on docker.io
```
[ ] Yes
[x] No
```
> RWA-2816-Remove dependency on docker.io

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2834
Extend suppression date for CVE-2023-35116
```
[ ] Yes
[x] No
```
> RWA-2834- Extend suppression date for CVE-2023-35116

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2872
Upgrade tomcat to fix new CVE's
```
[ ] Yes
[x] No
```
> RWA-2872 Upgrade tomcat to fix new CVE

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-2867
> Workflow API Postgres Flex server infra

- infrastructure/main.tf
Change secret names before migration
> Modify secret names after review

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2910
Extend suppression for  CVE-2023-35116
```
[ ] Yes
[x ] No
```
> RWA-2910: Extend suppression for  CVE-2023-35116

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2871
Update pact verifier publishResults settings in build.gradle
```
[ ] Yes
[x] No
```
> Update pact verifier publishResults settings in build.gradle

- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- charts/wa-workflow-api/values.yaml
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
- src/main/resources/application.yaml
- src/main/resources/db/migration/V1.0.4__grant_privs_to_reader_user.sql
https://tools.hmcts.net/jira/browse/RWA-2918
grant access to reader user
```
[x] Yes
[ ] No
```
> Rwa 2918 grant access to reader

- src/main/resources/db/migration/V1.0.4__grant_privs_to_reader_user.sql
https://tools.hmcts.net/jira/browse/RWA-2906
Reader User access deletion script
```
[ ] Yes
[x] No
```
> RWA-2918 Reader User action deletion script

- charts/wa-workflow-api/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/RWA-2984
Update AAT Config
```
[ ] Yes
[x] No
```
> RWA-2984 update AAT Config

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
- src/main/resources/db/migration/V1.0.5__grant_privs_to_reader_user_flexible_server.sql
https://tools.hmcts.net/jira/browse/RWA-2917
Updated values.yaml to point to Flexible Server Configuration
```
[x] Yes
[ ] No
```
> RWA-2917 Updated values.yaml to point to Flexible Server Configuration

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3014
Need to upgrade OWASP - wa-workflow-api
```
[ ] Yes
[x] No
```
> RWA-3014 Need to upgrade OWASP - wa-workflow-api

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/Application.java
https://tools.hmcts.net/jira/browse/RWA-3105
> Rwa 3105 upgrade checkstyle

- build.gradle
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/Application.java
https://tools.hmcts.net/jira/browse/RWA-3107
> Upgrading spring sec

- build.gradle
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdviceTest.java
https://tools.hmcts.net/jira/browse/RWA-3109
> Version Incompatibility fix

- .github/renovate.json
- README.md
Some more tuning to reduce noise and stop major upgrade PRs
> Tuning renovate

- .github/renovate.json
Correcting the group name so the branch name doesn't cause a build problem.
> Correcting group name

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3145
https://tools.hmcts.net/jira/browse/RWA-3148
> Updating Suppression expiry

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3225
```
[ ] Yes
[ X] No
```
> RWA-3225: Extend Suppression

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-3126
```
[ ] Yes
[ ] No
```
> RWA-3126: spotInstance config added

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3323
```
[ ] Yes
[x] No
```
> RWA-3323: Extend Suppression

- charts/wa-workflow-api/Chart.yaml
- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- charts/wa-workflow-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-3233
```
[ ] Yes
[ ] No
```
> RWA-3233: Upgraded Helm chart to 5.2

- charts/wa-workflow-api/Chart.yaml
Update to latest Java Chart version after wa-chart was upgraded.
https://tools.hmcts.net/jira/browse/RWA-3343
> Upgrade to latest Java chart version

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3387
```
[ ] Yes
[x] No
```
> RWA-3387: Extend Suppression for CVE-2023-35116

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/service/IdempotencyKeysRepositoryJpaTest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/idempotencykey/IdempotencyKeys.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/idempotency/IdempotencyKeysRepository.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/SecurityConfiguration.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/CallbackControllerAdviceTest.java
https://tools.hmcts.net/jira/browse/RWA-2372
```
[ ] Yes
[ ] No
```
> RWA-2372: Workflow API springboot upgrade

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-3487
```
[ ] Yes
[x ] No
```
> RWA-3487: Add env.TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3496
```
[ ] Yes
[x] No
```
> RWA-3496: Remove Suppression

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3517
```
[ ] Yes
[x] No
```
> RWA-3517: Upgrade dependencycheck to 10.0.2

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
https://tools.hmcts.net/jira/browse/RWA-3566
```
[ ] Yes
[x] No
```
> RWA-3566: Fix Code Smell

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-124
```
[ ] Yes
[ ] No
```
> remove sync

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-124
```
[ ] Yes
[ ] No
```
> Cme 124 reapply

- infrastructure/main.tf
- infrastructure/variables.tf
Reverts hmcts/wa-workflow-api#850
> Revert "Cme 124 reapply"

- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RWA-4098 
```
[ ] Yes
[ ] No
```
> RWA-4098: Updated preview camunda image pull location.

- Jenkinsfile_CNP
Reverts hmcts/wa-workflow-api#846
> Revert "remove sync"

- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RWA-4174 
```
[ ] Yes
[ ] No
```
> RWA-4174: Revert image Repo to hmctsprivate

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-25120
Amended fortify client dependency
```
[ ] Yes
[X] No
```
> Amended fortify client dependency

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- charts/wa-workflow-api/values.aat.template.yaml
- charts/wa-workflow-api/values.preview.template.yaml
- docker-pactbroker-compose.yml
https://tools.hmcts.net/jira/browse/RWA-4234
Enabling fortify scan in nightly, fixed fortify issues highlighted by PR run
```
[ ] Yes
[ ] No
```
> RWA-4234: re-enable fortify in nightly

- CODEOWNERS
https://tools.hmcts.net/jira/browse/RWA-4278
> Add WA Team as codeowners

- README.md
https://tools.hmcts.net/jira/browse/RWA-4160
Update ReadME file
```
[ ] Yes
[x] No
```
> RWA-3753 - test commit

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-4378
> Replace jitpack with ADO

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-4366
```
[ ] Yes
[x] No
```
> RWA-4366: Upgrade owasp

- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnResponse.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientService.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/idempotency/IdempotencyTaskService.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdvice.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdviceBase.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskRequest.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/ServiceDetails.java
- src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/Transition.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/PojoTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/WarningValuesTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/EvaluateDmnServiceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/IdempotencyTaskServiceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientServiceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/config/LaunchDarklyFeatureFlagProviderTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdviceTest.java
- src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4504
Removing a variety of codesmells hightlighted by sonarqube
```
[ ] Yes
[x] No
```
> RWA-4504: Workflow codesmells
